name: PracticeUI
configs:
  DEBUG: debug
  STAGING: release
  RELEASE: release
configFiles:
  DEBUG: PracticeUI/configs/debug.xcconfig
  STAGING: PracticeUI/configs/staging.xcconfig
  RELEASE: PracticeUI/configs/release.xcconfig
settings:
  CODE_SIGN_STYLE: Manual
  CODE_SIGN_IDENTITY: sign.identity
  DEVELOPMENT_TEAM: dev.team
  #CODE_SIGN_ENTITLEMENTS: 
  #FRAMEWORK_SEARCH_PATHS: Frameworks
options:
  createIntermediateGroups: true
  bundleIdPrefix: tw.idv.pokeduck
  deploymentTarget:
    iOS: 11.0
  #findCarthageFrameworks: false
  #carthageBuildPath: ../FrameworksA/
  #carthageExecutablePath: mint run Carthage/Carthage
  #carthageBuildPath: Frameworks
targets:
  PracticeUI:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    dependencies:
      #- carthage: RxSwift
        #CARTHAGE_BUILD_PATH: Frameworks
      - framework: Frameworks/RxSwift.framework
      - framework: Frameworks/RxCocoa.framework
      - framework: Frameworks/RxBlocking.framework
      - framework: Frameworks/RxRelay.framework
      - framework: Frameworks/RxTest.framework

    #configFiles:
    #  DEBUG: PracticeUI/configs/debug.xcconfig
    # STAGING: PracticeUI/configs/staging.xcconfig
    #  RELEASE: PracticeUI/configs/release.xcconfig
    settings:
        configs:
          DEBUG:
            CUSTOM_BUILD_SETTING: debug.idv.pokeduck
          STAGING:
            CUSTOM_BUILD_SETTING: staging.idv.pokeduck
          RELEASE:
            CUSTOM_BUILD_SETTING: release.idv.pokeduck
    sources: 
      - path: PracticeUI

